# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui files\tut4.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.show_popup = QtWidgets.QPushButton(self.centralwidget)
        self.show_popup.setGeometry(QtCore.QRect(240, 60, 291, 121))
        self.show_popup.setObjectName("show_popup")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.show_popup.clicked.connect(self.show_popup_window)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.show_popup.setText(_translate("MainWindow", "show_popup"))

    def show_popup_window(self):
        msg = QMessageBox()
        msg.setWindowTitle("Popup Window")
        msg.setText("This is a popup")
        # msg.setIcon(QMessageBox.Critical)
        # msg.setIcon(QMessageBox.Warning)
        # msg.setIcon(QMessageBox.Information)
        msg.setIcon(QMessageBox.Question)
        msg.setStandardButtons(QMessageBox.Retry | QMessageBox.Ignore | QMessageBox.Ok) # here default is Ok
        '''
            List of Buttons
                QMessageBox.Ok
                QMessageBox.Open
                QMessageBox.Save
                QMessageBox.Cancel
                QMessageBox.Close
                QMessageBox.Yes
                QMessageBox.No
                QMessageBox.Abort
                QMessageBox.Retry
                QMessageBox.Ignore
        '''
        msg.setDefaultButton(QMessageBox.Ignore)
        msg.setInformativeText("informative text, ya!")
        msg.setDetailedText("details")
        msg.buttonClicked.connect(self.popup_button)
        
        x = msg.exec_()
        
    def popup_button(self, i):
        print(i.text())


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
