# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui files\tut3.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.photo = QtWidgets.QLabel(self.centralwidget)
        self.photo.setGeometry(QtCore.QRect(190, 0, 381, 451))
        self.photo.setText("")
        self.photo.setPixmap(QtGui.QPixmap("ui files\\../../../Folders/sujal/photo.jpg"))
        self.photo.setScaledContents(True)
        self.photo.setObjectName("photo")
        self.old = QtWidgets.QPushButton(self.centralwidget)
        self.old.setGeometry(QtCore.QRect(0, 450, 401, 61))
        self.old.setObjectName("old")
        # self.old.setText("Old")
        self.new_2 = QtWidgets.QPushButton(self.centralwidget)
        self.new_2.setGeometry(QtCore.QRect(400, 450, 401, 61))
        self.new_2.setObjectName("new_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.old.clicked.connect(self.show_old)
        self.new_2.clicked.connect(self.show_new)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.old.setText(_translate("MainWindow", "Old"))
        self.new_2.setText(_translate("MainWindow", "New"))

    def show_old(self):
        self.photo.setPixmap(QtGui.QPixmap("ui files\\../../../Folders/sujal/photo.jpg"))

    def show_new(self):
        self.photo.setPixmap(QtGui.QPixmap("ui files\\../../../Folders/sujal/myimage.jpg"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
